<a href="https://colab.research.google.com/github/moksliukai/mokslai2018/blob/master/Uzduotys_2024_03_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2024-03-21

Padalinkite intervalą nuo -1.3 iki 2.5 tolygiai į 64 dalis.

In [3]:
import numpy as np
d = np.linspace(-1.3,2.5,64)
print(d)
print(d.shape)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]
(64,)


Sugeneruokite masyvą dydžio 3n ir užpildykite jį cikliniu šablonu [1, 2, 3].

In [1]:
import numpy as np
def masyvo_užpildas1(n):
    x = np.zeros(3*n, dtype=int)
    np.putmask(x, np.ones_like(x), [1,2,3])
    return x

def masyvo_užpildas2(n):
    return np.tile([1,2,3],n)

masyvo_užpildas1(7), masyvo_užpildas2(7)

(array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]),
 array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]))

Sukurkite masyvą iš pirmųjų 10 nelyginių sveikųjų skaičių.

In [2]:
def pirmieji1(n):
    x = np.full(n,2)
    x[0] = 1
    return np.cumsum(x)

def pirmieji2(n):
    return np.arange(n)*2 + 1

def pirmieji3(n):
    return np.arange(1, 2*n, 2)

print(pirmieji1(10))
a = pirmieji2(10)
print(a)
print(pirmieji3(10))

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]


Parašykite funkciją, į kurią reikia įvesti kvadratinės lygties koeficientus ir kuri grąžina du sprendinius. Įtraukite ir atvejus, kai narys prie kvadrato yra nulinis arba diskriminantas neigiamas.

Slidininkai 10 km rungtyje startuoja pagal atrankos etapo rezultatus. Slidininkas startuoja tiek laiko vėliau už lyderį, kiek laiko nuo jo yra atsilikęs.

Parašykite programą, kuri pateiktų slidininkų rezultatų sąrašą pagal trasoje sugaištą laiką didėjančiai. Per vienodą laiką nušliuožę slidininkai turi būti rašomi abėcėliškai pagal simbolių eilutę, kurioje yra slidininką identifikuojanti informacija.

Pradiniai duomenys

Duomenys pateikiami tekstiniame faile U2.txt. Visi skaičiai yra sveikieji.

Duomenų faile įrašyta:

Pirmoje eilutėje užrašytas startuojančių slidininkų skaičius n (1 \leq n
\leq 30).
Tolesnėse n eilučių atsitiktine tvarka surašyti slidininkų starto duomenys. Kiekvieno slidininko duomenys užrašyti atskiroje eilutėje: pirmose 20 pozicijų yra simbolių eilutė, kurioje pateikta slidininką identifikuojanti informacija; po to starto laikas: valanda, minutė ir sekundė, atskirtos vienu tarpo simboliu.
Toliau užrašytas finišavusių slidininkų skaičius m (1 \leq m \leq 30).
Tolesnėse m eilučių surašyti slidininkų finišo duomenys. Kiekvieno slidininko duomenys užrašyti atskiroje eilutėje: pirmose 20 pozicijų yra simbolių eilutė, kurioje pateikta slidininką identifikuojanti informacija; po to finišo laikas: valanda, minutė ir sekundė, atskirtos vienu tarpo simboliu.
Rezultatai

Rezultatus įrašykite tekstiniame faile U2rez.txt.

Vienoje eilutėje užrašykite vieno slidininko duomenis: pirmose 20 pozicijų – simbolių eilutę, kurioje pateikta slidininką identifikuojanti informacija, atskirta vienu tarpo simboliu, po to slidininko rezultatas: minutės ir sekundės, atskirtos vienu tarpo simboliu. 10 km rungtyje maksimalus slidininko sugaištas laikas yra ne daugiau kaip valanda.Jeigu slidininkas nepasiekė finišo(jo nėra finišavusiųjų sąraše), tai rezultatų sąraše jo neturi būti.
Rezultatai turi būti surikiuoti pagal trasoje sugaištą laiką didėjančiai. Per vienodą laiką nušliuožę slidininkai rašomi abėcėliškai pagal simbolių eilutę, kurioje yra slidininką identifikuojanti informacija.
Nurodymai

Sukurkite ir parašykite funkciją1, kuri surikiuoja rezultatus.
Sukurkite ir parašykite funkciją, kuri spausdina rezultatus tekstiniame faile.
Programoje nenaudokite sakinių, skirtų darbui su ekranu.
Duomenų ir rezultatų pavyzdžiai\
6\
Petras A. Petraitis 15 20 00\
Jurgis Jurgutis     16 12 12\
Rimas Jonas         15 15 59\
Zigmas Nosis        16 23 9\
Romas Senasis       15 15 15\
Rytis Uosis Ainis   16 23 9\
5\
Zigmas Nosis        16 43 15\
Petras A. Petraitis 15 50 10\
Romas Senasis       16 5 35\
Rytis Uosis Ainis   16 55 59\
Jurgis Jurgutis     16 42 22\

Gautas rezultatas\

Zigmas Nosis        20 6\
Jurgis Jurgutis     30 10\
Petras A. Petraitis 30 10\
Rytis Uosis Ainis   32 50\
Romas Senasis       50 20